name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd 2015 && cargo build --verbose
    #- name: Run tests
    #  run: cd 2015 && cargo test --verbose
      
      # lol phind.com
    - name: Run tests
      run: |
        find . -type d -regex '\./[0-9]\{4\}$' | while IFS= read -r dir; do
          (cd "$dir" && cargo test --verbose);
        done
