name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: for dir in 2015 2016 2017; do (echo "h1. $dir" && cd "$dir" && cargo build --verbose); done
    - name: Run tests
      run: for dir in 2015 2016 2017; do (echo "h1. $dir" && cd "$dir" && cargo test --verbose); done
