name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Find Years
      run: echo "{years}=${{ ls -d }}" >> "$GITHUB_ENV"
    - name: Build
      run: cd 2015 && cargo build --verbose
      
      # lol phind.com
    - name: Run tests
      run: for dir in "2015 2016 2017"; do (cd "$dir" && cargo test --verbose); done
